package com.deepresearch.service;

import com.deepresearch.model.KnowledgeChunk;
import com.deepresearch.model.ParsedDocument;
import com.deepresearch.web.dto.RetrievalEvalRequest;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

import static org.assertj.core.api.Assertions.assertThat;

class ContextEvaluationDatasetTest {

    private static final Path DOCUMENT = Path.of("testdata", "kb", "context-engineering-long-manual.md");
    private static final Path DATASET = Path.of("testdata", "eval", "context-engineering-cases.jsonl");
    private static final String TITLE = "DeepResearch W6/W7 长文档验证手册";

    @Test
    void expectedChunkKeysMustExistInCurrentDocumentAndChunkingStrategy() throws Exception {
        DocumentParserService parser = new DocumentParserService();
        ParsedDocument document = parser.parseFile(TITLE, DOCUMENT.getFileName().toString(), Files.readAllBytes(DOCUMENT));
        List<KnowledgeChunk> chunks = new StructuralChunker(800, 120, 80).chunk("dataset-consistency", document);
        Set<String> actualKeys = chunks.stream()
                .map(chunk -> document.filename() + "#" + chunk.sectionPath() + "#" + chunk.chunkIndex())
                .collect(Collectors.toSet());

        ObjectMapper objectMapper = new ObjectMapper();
        Map<String, List<String>> staleKeysByCase = new LinkedHashMap<>();
        for (String line : Files.readAllLines(DATASET)) {
            RetrievalEvalRequest.Case evalCase = objectMapper.readValue(line, RetrievalEvalRequest.Case.class);
            List<String> staleKeys = evalCase.expectedChunkKeys().stream()
                    .filter(expected -> !actualKeys.contains(expected))
                    .toList();
            if (!staleKeys.isEmpty()) {
                staleKeysByCase.put(evalCase.id(), staleKeys);
            }
        }

        assertThat(staleKeysByCase)
                .as("context evaluation labels must match keys generated by the current parser and chunker")
                .isEmpty();
    }
}
